version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "npm install && npm run build && npm run start"
    # env_file:     // if you need to env file then uncomment this two lines
    #   - ./.env
    ports: 
      - 12801:3000
    volumes:
      - .:/app
    networks:
      - common-network

networks:
  common-network:
    driver: bridge