version: '3'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "npm install && npm run build && npm run start"
    env_file:
      - ./.env
    ports: 
      - ${HOST_PORT}:3000
    volumes:
      - .:/app
    networks:
      - common-network

networks:
  common-network:
    driver: bridge